import { Event } from "@/types";

export const mockEvents: Event[] = [
  {
    id: 1,
    title: "Rock in Rio 2025",
    description:
      "O maior festival de música do mundo retorna ao Parque Olímpico com um lineup que mistura rock clássico, pop internacional e artistas nacionais consagrados. Três dias de shows inesquecíveis.",
    date: "2025-09-15T16:00:00.000Z",
    location: "Parque Olímpico, Rio de Janeiro - RJ",
    price: 595.0,
    imageUrl: "https://picsum.photos/seed/rockinrio/800/400",
    capacity: 100000,
    availableTickets: 2500,
    category: "Festival",
  },
  {
    id: 2,
    title: "Lollapalooza Brasil 2025",
    description:
      "Festival multicultural no Autódromo de Interlagos com mais de 70 atrações distribuídas em 4 palcos. Gastronomia, arte urbana e experiências imersivas.",
    date: "2025-03-28T12:00:00.000Z",
    location: "Autódromo de Interlagos, São Paulo - SP",
    price: 480.0,
    imageUrl: "https://picsum.photos/seed/lollapalooza/800/400",
    capacity: 75000,
    availableTickets: 8200,
    category: "Festival",
  },
  {
    id: 3,
    title: "Fábio Jr. - Turnê 50 Anos",
    description:
      "O cantor celebra cinco décadas de carreira com um show repleto de sucessos que marcaram gerações. Uma noite de pura emoção e nostalgia.",
    date: "2025-04-12T21:00:00.000Z",
    location: "Espaço das Américas, São Paulo - SP",
    price: 220.0,
    imageUrl: "https://picsum.photos/seed/fabiojr/800/400",
    capacity: 8000,
    availableTickets: 340,
    category: "Show",
  },
  {
    id: 4,
    title: "Hamlet - Cia. Brasileira de Teatro",
    description:
      "Releitura contemporânea do clássico de Shakespeare com cenografia minimalista e iluminação expressionista. Abordagem visceral e política ao texto original.",
    date: "2025-05-20T19:30:00.000Z",
    location: "Teatro Alfa, São Paulo - SP",
    price: 180.0,
    imageUrl: "https://picsum.photos/seed/hamlet/800/400",
    capacity: 1100,
    availableTickets: 15,
    category: "Teatro",
  },
  {
    id: 5,
    title: "Stand-Up: Comediantes da Noite",
    description:
      "Os maiores nomes da comédia stand-up em uma noite única. Humor ácido, observações do cotidiano e muito improviso.",
    date: "2025-04-05T20:00:00.000Z",
    location: "Casa de Cultura Laura Alvim, Rio de Janeiro - RJ",
    price: 90.0,
    imageUrl: "https://picsum.photos/seed/standup/800/400",
    capacity: 350,
    availableTickets: 0,
    category: "Stand-up",
  },
  {
    id: 6,
    title: "Flamengo x Palmeiras - Brasileirão",
    description:
      "O clássico do futebol brasileiro no Maracanã. Dois dos maiores times do país em partida decisiva pelo Campeonato Brasileiro Série A.",
    date: "2025-06-08T16:00:00.000Z",
    location: "Estádio Maracanã, Rio de Janeiro - RJ",
    price: 150.0,
    imageUrl: "https://picsum.photos/seed/futebol/800/400",
    capacity: 78000,
    availableTickets: 12000,
    category: "Esporte",
  },
  {
    id: 7,
    title: "Cirque du Soleil - Amaluna",
    description:
      "Acrobacias impressionantes, figurinos deslumbrantes e uma trilha sonora original que transporta o público para um mundo mágico.",
    date: "2025-07-15T20:00:00.000Z",
    location: "Parque Villa-Lobos, São Paulo - SP",
    price: 350.0,
    imageUrl: "https://picsum.photos/seed/cirque/800/400",
    capacity: 2500,
    availableTickets: 890,
    category: "Show",
  },
  {
    id: 8,
    title: "Festival de Jazz de São Paulo",
    description:
      "Quatro dias dedicados ao jazz com artistas brasileiros e internacionais. Shows ao ar livre, workshops e jam sessions até a madrugada.",
    date: "2025-08-22T18:00:00.000Z",
    location: "Parque Ibirapuera, São Paulo - SP",
    price: 120.0,
    imageUrl: "https://picsum.photos/seed/jazz/800/400",
    capacity: 5000,
    availableTickets: 3200,
    category: "Festival",
  },
  {
    id: 9,
    title: "O Fantasma da Ópera",
    description:
      "O musical mais famoso do mundo em nova temporada brasileira. Produção fiel ao espetáculo da Broadway com elenco nacional de alto nível.",
    date: "2025-05-10T20:00:00.000Z",
    location: "Teatro Renault, São Paulo - SP",
    price: 280.0,
    imageUrl: "https://picsum.photos/seed/opera/800/400",
    capacity: 1500,
    availableTickets: 420,
    category: "Teatro",
  },
];
